### ISSUE TITLE
Regression (redis client seem to not use password)

### ISSUE THREAD

**Issue by davidfischer-ch** [niwibe/django-redis#112]
Using djang-redis 01bf4279f13194f2c99dc7b9d4b93929c951c948 with redis_cache works:

    CACHES = {
        'default': {
            'BACKEND': 'redis_cache.cache.RedisCache',
            'LOCATION': '{{ caching_master.host }}:{{ caching_master.port }}:1',
            'OPTIONS': {
                'CLIENT_CLASS': 'redis_cache.client.DefaultClient',
                'COMPRESS_MIN_LEN': 10,
                'IGNORE_EXCEPTIONS': True,  # Better to have a cache miss than the website unavailable!
                'PASSWORD': '{{ cache.password }}'
            }
        }
    }

But when upgrading djang-redis to master and using django_redis, it doesn't:

    Traceback (most recent call last):
      File "/var/project/test/server/project/tests/api/account.py", line 57, in test_num_queries
        user = self.login()
      File "/var/project/test/server/project/tests/mixins/models.py", line 211, in login
        self.assertEqual(self.client.login(username=username, password=password), should_succeed)
      File "/var/project/test/venv/src/django/django/test/client.py", line 585, in login
        if self.session:
      File "/var/project/test/venv/src/django/django/test/client.py", line 406, in _session
        s.save()
      File "/var/project/test/venv/src/django/django/contrib/sessions/backends/cache.py", line 56, in save
        result = func(self.cache_key,
      File "/var/project/test/venv/src/django/django/contrib/sessions/backends/cache.py", line 19, in cache_key
        return KEY_PREFIX + self._get_or_create_session_key()
      File "/var/project/test/venv/src/django/django/contrib/sessions/backends/base.py", line 162, in _get_or_create_session_key
        self._session_key = self._get_new_session_key()
      File "/var/project/test/venv/src/django/django/contrib/sessions/backends/base.py", line 156, in _get_new_session_key
        if not self.exists(session_key):
      File "/var/project/test/venv/src/django/django/contrib/sessions/backends/cache.py", line 63, in exists
        return (KEY_PREFIX + session_key) in self._cache
      File "/var/project/test/venv/src/django/django/core/cache/backends/base.py", line 182, in __contains__
        return self.has_key(key)
      File "/var/project/test/venv/src/django-redis/django_redis/cache.py", line 26, in _decorator
        return method(self, *args, **kwargs)
      File "/var/project/test/venv/src/django-redis/django_redis/cache.py", line 125, in has_key
        return self.client.has_key(*args, **kwargs)
      File "/var/project/test/venv/src/django-redis/django_redis/client/default.py", line 427, in has_key
        return client.exists(key)
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/client.py", line 838, in exists
        return self.execute_command('EXISTS', name)
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/client.py", line 564, in execute_command
        connection.send_command(*args)
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/connection.py", line 556, in send_command
        self.send_packed_command(self.pack_command(*args))
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/connection.py", line 532, in send_packed_command
        self.connect()
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/connection.py", line 440, in connect
        self.on_connect()
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/connection.py", line 514, in on_connect
        if nativestr(self.read_response()) != 'OK':
      File "/var/project/test/venv/lib/python3.4/site-packages/redis/connection.py", line 574, in read_response
        raise response
    redis.exceptions.ResponseError: NOAUTH Authentication required.

**Comment by niwibe** [comment]
Now fixed! https://github.com/niwibe/django-redis/commit/f4b5d60ec2b2d36beb3434adb14d7521401e91b8

Thanks!

**Comment by TonyPythoneer** [comment]
After I read the doc, I tried to run and encounter the same bug.

Suppose my password is `abc123`

I set `LOCATION` to `redis://abc123@127.0.0.1:6379/0`, it causes the same bug: `redis.exceptions.ResponseError: NOAUTH Authentication required.`

When I have read this issue, I know I have set `:` in front of `password`.

So I have to set `redis://:abc123@127.0.0.1:6379/0`, I can continue to leverage django_redis.

**Comment by niwinz** [comment]
I'm not clearly understand, with `redis://:abc123@127.0.0.1:6379/0` everything works correctly?

**Comment by TonyPythoneer** [comment]
Because some people are like me, they set the password without the `:` and cause the bug.

**Comment by niwinz** [comment]
Hmm, but it not seems to be bug. If your server requires a password it should be set after ":". This is how the url syntax work.

If you are put password in the username field of the URI it is expected to not work...

**Comment by TonyPythoneer** [comment]
You are right. It's my  syntax error, not bug.
Currently I have read your fix and lookup the source code how to set redis with password, so I have known.
